### ISSUE TITLE
Packaging for via Flatpack/Flathub?

### ISSUE THREAD

**Issue by SchoolGuy** [umlet/umlet#640]
I am using this via the ZIP for ages now, since Java packaging is natively hard on most Linux Distros (I mean bundling stuff in a DEB/RPM is just pure evil, although common practice). I would love if we could instead just package a Flatpak and distribute it on Flathub.

I never did this myself but if the developers don't want to spend the time but would allow it, I would offer my help and time to maintain the Flatpak.

**Comment by afdia** [comment]
The only official Umlet distributions are those from www.umlet.com, Eclipse Marketplace and VSCode Marketplace.

Everything else (like the packages from some Linux distributions) is maintained by other people.
We also don't have any experience with Flatpak, but if you want to maintain a package there it would be nice to have (but I would suggest that you mention somewhere that the distribution is not managed by the umlet team)

By the way we are experimenting with https://github.com/fvarrui/JavaPackager to package umlet+JRE to avoid a dependency to a Java installation (in addition to our zip package).
There is a branch https://github.com/umlet/umlet/tree/packaging_jre where we successfully built a Windows Umlet versions which includes the JRE (with an overhead of ~40mb). To finalize the effort we would have to adapt our maven build to include a  section which downloads a version of adoptjdk for every OS and create a bundle for every OS (Linux, Windows, Macos)

**Comment by SchoolGuy** [comment]
Yes I agree with your points but from the perspective of the user it is easier having to type in `umlet` or have a start menu entry, then having a ZIP file "somewhere" on your system and the need to check for updates yourself. A package manager will always upgrade the software and you profit from updates. Because your bundled JRE will never recieve the latest Security and Stability updates from Upstream. A user will never download your Umlet weekly just to get the latest rebuild of your Bundle. Anyway...

I would consider your message an allowance to create such a package and maintain it for you. This is great news for me and will make my life much easier. Hopefully I can get you some users through the flatpack. Let's see. I will update this issue for my progress. I am finishing my apprenticeship currently, so everything is a littlebit slower as I am focusing on this currently...

**Comment by SchoolGuy** [comment]
P.S.: If possible I would love if you could assign me to this issue so I see it in my assigned issues on GH... :)

**Comment by afdia** [comment]
Ok thanks, I have assigned the issue to you.

**Comment by zocker-160** [comment]
@SchoolGuy any update on this? I would be interested in a Flatoak and willing to help you to get it to Flathub.

**Comment by SchoolGuy** [comment]
@zocker-160 I was sidetracked. Sorry. I completely forgot about this because my existing installation worked like a charm. I will start this today. :)

**Comment by SchoolGuy** [comment]
Okay the process is fairly straightforward it seems. It is documented here: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by SchoolGuy** [comment]
Okay even though the process is straightforward, the execution is not it seems. The reason for this is quite satisfying actually: Flathub denies network access during the build time. Thus we have to work around this.

An example how this could look in the end is the following flathub entry: https://github.com/flathub/es.estoes.wallpaperDownloader

An explanation of the hows and whys can be found here: https://github.com/flatpak/flatpak-builder/issues/58#issuecomment-781508777

I will try to drive this in my fork and once I have an idea of the execution, I will try to open a WIP PR against all required repositories.

**Comment by zocker-160** [comment]
@SchoolGuy ah cool to hear from you, I personally already have experience with publishing on Flathub since I have helped other devs to do so.

My question was more like if I can help you in any way with this.

**Comment by SchoolGuy** [comment]
@zocker-160 Ahhh thanks a lot but I believe the Problem is Maven wanting to build something online, rather then offline. I have encountered this already with the openSUSE Buildservice already and solved it in the past. So it just takes time for me.

**Comment by zocker-160** [comment]
@SchoolGuy I created a working Flatpak using the prebuilt jar file

```yml
app-id: com.umlet.Umlet
runtime: org.freedesktop.Platform
runtime-version: "21.08"
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk17

rename-icon: umlet_logo
rename-desktop-file: umlet.desktop
command: umlet

finish-args:
    - --env=PATH=/app/jre/bin:/usr/bin:/app/bin
    - --env=UMLET_HOME=/app/lib/umlet
    - --share=ipc
    - --socket=wayland
    - --socket=fallback-x11
    - --device=dri
    - --filesystem=home

modules:
    - name: openjdk
      buildsystem: simple
      build-commands:
        - /usr/lib/sdk/openjdk17/install.sh

    - name: Umlet
      buildsystem: simple
      build-commands:
        - install -D -m755 umlet.jar -t /app/lib/umlet
        - cp -a  {img,lib,palettes,custom_elements} /app/lib/umlet
        - install -D -m755 umlet.sh /app/bin/umlet
        # fix start command
        - sed -i -e 's/Exec=java -Dsun.java2d.xrender=f -jar umlet.jar/Exec=umlet/g' umlet.desktop
        - install -D -m644 umlet.desktop -t /app/share/applications
        - install -D -m644 img/umlet_logo.png -t /app/share/icons/hicolor/512x512/apps
#      post-install:
        # FIXME: create metainfo file
#        - install -D -m644 metainfo.xml -t /app/share/metainfo
      sources:
        - type: archive
          url: https://www.umlet.com/download/umlet_15_0/umlet-standalone-15.0.0.zip
          sha256: 81dbe1a981b2ac5b90861ae4176eb05dbdd340b4422e6e7dfee4b14cf9877401
```
